# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 00:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blooming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=40, null=True)),
                ('last_name', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.CharField(blank=True, max_length=40, null=True)),
                ('professor', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='info',
            name='_classrooms',
        ),
        migrations.RemoveField(
            model_name='info',
            name='user',
        ),
        migrations.RenameField(
            model_name='classroom',
            old_name='serial',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='classroom',
            name='_topics',
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
