# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blooming', '0002_auto_20170319_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassroomBloomer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bloomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroombloomer_bloomer', to='blooming.Bloomer')),
            ],
        ),
        migrations.AlterField(
            model_name='classroom',
            name='description',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AddField(
            model_name='classroombloomer',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroombloomer_classroom', to='blooming.Classroom'),
        ),
    ]
