# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 22:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blooming', '0004_auto_20170319_1811'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicClassroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicclassroom_classroom', to='blooming.Classroom')),
            ],
        ),
        migrations.CreateModel(
            name='TopicDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='topic',
            name='_antes',
        ),
        migrations.AlterField(
            model_name='topic',
            name='text',
            field=models.CharField(max_length=80),
        ),
        migrations.AddField(
            model_name='topicdependency',
            name='ante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicdependency_ante', to='blooming.Topic'),
        ),
        migrations.AddField(
            model_name='topicdependency',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicdependency_post', to='blooming.Topic'),
        ),
        migrations.AddField(
            model_name='topicclassroom',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topicclassroom_topic', to='blooming.Topic'),
        ),
    ]
