# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-04 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bloomerprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='submit_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
