# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 22:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=12, unique=True)),
                ('text', models.TextField()),
                ('accepted', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=9, unique=True)),
                ('text', models.TextField()),
                ('kind', models.CharField(choices=[('b', 'True or false'), ('m', 'Multiple choice'), ('o', 'Open question'), ('t', 'Teacher evaluated question'), ('w', 'Work to deliver to the teacher')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('recollection', models.BooleanField(default=False)),
                ('hindex', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SerieSerie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serieserie_ante', to='content.Serie')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serieserie_post', to='content.Serie')),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=6, unique=True)),
                ('kind', models.IntegerField(blank=True, choices=[(1, 'remembering'), (2, 'understanding'), (3, 'applying'), (4, 'analyzing'), (5, 'evaluating'), (6, 'creating')], null=True)),
                ('mobile', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=80)),
                ('serie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_serie', to='content.Serie')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_topic', to='content.Topic'),
        ),
        migrations.AddField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='option_question', to='content.Question'),
        ),
    ]
